import { ColorScheme } from '@/hooks/useTheme';
import { Dimensions, StyleSheet } from 'react-native';

const { height: SCREEN_HEIGHT } = Dimensions.get('window');

export const SHEET_HEIGHT = SCREEN_HEIGHT * 0.68;

export const createBudgetSheetStyles = (colors: ColorScheme) =>
  StyleSheet.create({
    backdrop: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
    },
    sheet: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      height: SHEET_HEIGHT,
      backgroundColor: colors.surface,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      paddingHorizontal: 24,
      paddingTop: 12,
      paddingBottom: 32,
    },
    handle: {
      width: 40,
      height: 4,
      borderRadius: 2,
      backgroundColor: colors.border,
      alignSelf: 'center',
      marginBottom: 16,
    },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 24,
    },
    title: {
      fontSize: 22,
      fontWeight: '800',
      color: colors.text,
      letterSpacing: -0.5,
    },
    closeButton: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: colors.bg,
      justifyContent: 'center',
      alignItems: 'center',
    },
    label: {
      fontSize: 14,
      fontWeight: '600',
      color: colors.textMuted,
      marginBottom: 8,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    dropdownTrigger: {
      backgroundColor: colors.backgrounds.input,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 14,
      paddingHorizontal: 16,
      paddingVertical: 14,
      marginBottom: 10,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    dropdownTriggerDisabled: {
      opacity: 0.6,
    },
    dropdownValue: {
      fontSize: 16,
      fontWeight: '700',
      color: colors.text,
      marginBottom: 4,
    },
    dropdownValueDisabled: {
      color: colors.textMuted,
    },
    rangeText: {
      fontSize: 13,
      color: colors.textMuted,
    },
    dropdownMenu: {
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 14,
      backgroundColor: colors.bg,
      marginBottom: 12,
      overflow: 'hidden',
    },
    dropdownOption: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 14,
      paddingVertical: 12,
    },
    dropdownOptionText: {
      fontSize: 15,
      color: colors.text,
      fontWeight: '600',
    },
    dropdownOptionTextSelected: {
      color: colors.primary,
    },
    lockedHint: {
      color: colors.textMuted,
      fontSize: 13,
      marginBottom: 12,
      lineHeight: 18,
    },
    input: {
      backgroundColor: colors.backgrounds.input,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 14,
      paddingHorizontal: 16,
      paddingVertical: 14,
      fontSize: 16,
      color: colors.text,
      marginBottom: 20,
    },
    categoryRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
      marginBottom: 20,
    },
    categoryChip: {
      paddingHorizontal: 16,
      paddingVertical: 10,
      borderRadius: 20,
      backgroundColor: colors.bg,
      borderWidth: 1,
      borderColor: colors.border,
    },
    categoryChipSelected: {
      backgroundColor: colors.primary,
      borderColor: colors.primary,
    },
    categoryChipText: {
      fontSize: 14,
      fontWeight: '600',
      color: colors.text,
    },
    categoryChipTextSelected: {
      color: '#FFFFFF',
    },
    accountList: {
      gap: 10,
      marginBottom: 20,
    },
    accountOption: {
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 14,
      backgroundColor: colors.backgrounds.input,
      paddingHorizontal: 14,
      paddingVertical: 12,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    accountOptionSelected: {
      borderColor: colors.primary,
      backgroundColor: colors.bg,
    },
    accountName: {
      fontSize: 15,
      fontWeight: '700',
      color: colors.text,
      marginBottom: 2,
    },
    accountType: {
      fontSize: 13,
      color: colors.textMuted,
    },
    accountBalance: {
      fontSize: 14,
      fontWeight: '700',
      color: colors.success,
    },
    emptyAccounts: {
      borderWidth: 1,
      borderStyle: 'dashed',
      borderColor: colors.border,
      borderRadius: 14,
      paddingHorizontal: 14,
      paddingVertical: 18,
      marginBottom: 20,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.backgrounds.input,
    },
    emptyAccountsText: {
      color: colors.textMuted,
      fontSize: 14,
      textAlign: 'center',
      lineHeight: 20,
    },
    alertOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.45)',
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 24,
    },
    alertCard: {
      width: '100%',
      maxWidth: 360,
      borderRadius: 24,
      backgroundColor: colors.surface,
      paddingHorizontal: 24,
      paddingVertical: 24,
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.18,
      shadowRadius: 18,
      elevation: 12,
    },
    alertIconWrap: {
      width: 56,
      height: 56,
      borderRadius: 28,
      backgroundColor: colors.backgrounds.input,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 14,
    },
    alertTitle: {
      fontSize: 20,
      fontWeight: '800',
      color: colors.text,
      marginBottom: 8,
      textAlign: 'center',
    },
    alertMessage: {
      fontSize: 14,
      lineHeight: 21,
      color: colors.textMuted,
      textAlign: 'center',
      marginBottom: 20,
    },
    alertButton: {
      width: '100%',
      borderRadius: 14,
      overflow: 'hidden',
    },
    alertButtonGradient: {
      paddingVertical: 14,
      alignItems: 'center',
      justifyContent: 'center',
    },
    alertButtonText: {
      fontSize: 15,
      fontWeight: '700',
      color: '#FFFFFF',
    },
    submitButton: {
      borderRadius: 16,
      overflow: 'hidden',
      marginTop: 8,
    },
    submitGradient: {
      paddingVertical: 16,
      alignItems: 'center',
      justifyContent: 'center',
    },
    submitText: {
      fontSize: 16,
      fontWeight: '700',
      color: '#FFFFFF',
    },
  });
